### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by grzegorz914** [unknownskl/homebridge-smartglass#7]
After installing and configuring this plugins we have memory leak:
Homebridge 4.5
RPI4
Node.js 10.16

`(node:2196) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added. Use emitter.setMaxListeners() to increase limit`

Thanks

**Comment by grzegorz914** [comment]
After two day working no space left on device, please fix this memory leak.

thanks

**Comment by ychieux** [comment]
Hello there!

I am facing a similar issue. When the XBOX is on, I can control it without issue with the remote and can issue a shutdown command thru the HomeKit.

But once has been turned off, the smartglass plugins throws continuously 'failed to connect' errors when you attempt to send power on / off commands to the XBOX.

If I manually turn on the XBOX using the controller, it causes homebridge to crash once smartglass plugin restablishes its connection.

Note: the XBOX is connected over WiFi.

```
[8/26/2019, 8:08:23 PM] [Xbox One S] Setting Device Power State...
[8/26/2019, 8:08:23 PM] [Xbox One S] 1
[8/26/2019, 8:08:33 PM] [Xbox One S] Setting key state...
[8/26/2019, 8:08:33 PM] [Xbox One S] Send input key: right
[8/26/2019, 8:08:33 PM] [Xbox One S] Setting Device Power State...
[8/26/2019, 8:08:33 PM] [Xbox One S] 1
[8/26/2019, 8:08:34 PM] [Xbox One S] Setting key state...
[8/26/2019, 8:08:34 PM] [Xbox One S] Send input key: down
[8/26/2019, 8:08:41 PM] [Xbox One S] Setting Device Power State...
[8/26/2019, 8:08:41 PM] [Xbox One S] 0
Failed to connect to xbox: false
(node:8928) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added. Use emitter.setMaxListeners() to increase limit
Failed to connect to xbox: false
Failed to connect to xbox: false
(node:8928) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_discovery_response listeners added. Use emitter.setMaxListeners() to increase limit
(node:8928) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_timeout listeners added. Use emitter.setMaxListeners() to increase limit
Failed to connect to xbox: false
(node:8928) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_json listeners added. Use emitter.setMaxListeners() to increase limit
Failed to connect to xbox: false
_**[...] the message "Failed to connect to xbox: false" repeats continuously until I manually switch on the XBOX**_
Failed to connect to xbox: false
[8/26/2019, 8:36:03 PM] [Xbox One S] Setting Device Power State...
[8/26/2019, 8:36:03 PM] [Xbox One S] 1
Failed to connect to xbox: false
Failed to connect to xbox: false
[8/26/2019, 8:38:56 PM] [Xbox One S] Setting Device Power State...
[8/26/2019, 8:38:56 PM] [Xbox One S] 1
[8/26/2019, 8:39:01 PM] [Xbox One S] Setting Device Power State...
[8/26/2019, 8:39:01 PM] [Xbox One S] 0
Failed to connect to xbox: false
Failed to connect to xbox: false
**_XBOX switched on manually_**
Xbox succesfully connected!
Xbox succesfully connected!
[8/26/2019, 8:39:34 PM] TypeError: this._smartglass._console.get_requestnum is not a function
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/channels/systeminput.js:42:47)
    at EventEmitter.emit (events.js:203:15)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/events.js:112:23)
    at EventEmitter.emit (events.js:198:13)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:234:33)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
[8/26/2019, 8:39:34 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by unknownskl** [comment]
Thanks for the extensive explanation! This will help me a lot to reproduce the error. (I knew it was there, but it was hard for me to reproduce.)

I will take a look soon

**Comment by unknownskl** [comment]
Check out the new 0.13 update. It fixes a lot of bugs.

**Comment by ychieux** [comment]
After updating to 0.13, I can confirm that the previous error is solved.
Nevertheless, once the XBOX powered off using homekit, I am unable to power it back on.
I wonder if using WIFI on the XBOX could be the culprit...

**Comment by unknownskl** [comment]
Powering it back on required the console to be in standby. Aside from that the poweron function is a bit bugged sometimes. Happens with the official Xbox App too sadly.

**Comment by grzegorz914** [comment]
Hi,
working much better now but displayed name of inputs are not correct, for example Microsoft Store is displayed as TV.

**Comment by unknownskl** [comment]
Thats correct.. Not all the titles are supported. You can add them yourself via the config if you want to have the right names in Homekit.

**Comment by 400HPMustang** [comment]
> Thats correct.. Not all the titles are supported. You can add them yourself via the config if you want to have the right names in Homekit.

Do you happen to know how I could add Hulu and Netflix as inputs?

**Comment by muzzymate** [comment]
@400HPMustang - See here. As of version 13, the URI information is logged to the Homebridge console and than that can be added to your config.json file as additional "apps"

https://github.com/unknownskl/homebridge-smartglass/issues/8
